export const getAllBlogs = async (req: any, res: any) => {
	try {
	} catch (error: any) {
		console.log("error at getAllBlogs: ", error);
		res.status(500).json({
			message: error.message,
		});
	}
};

export const getSingleBlog = async (req: any, res: any) => {
	try {
	} catch (error: any) {
		console.log("error at getSingleBlog: ", error);
		res.status(500).json({
			message: error.message,
		});
	}
};

export const addComment = async (req: any, res: any) => {
	try {
	} catch (error: any) {
		console.log("error at addComment: ", error);
		res.status(500).json({
			message: error.message,
		});
	}
};

export const getAllComments = async (req: any, res: any) => {
	try {
	} catch (error: any) {
		console.log("error at getAllComments: ", error);
		res.status(500).json({
			message: error.message,
		});
	}
};

export const deleteComment = async (req: any, res: any) => {
	try {
	} catch (error: any) {
		console.log("error at deleteComment: ", error);
		res.status(500).json({
			message: error.message,
		});
	}
};

export const saveBlog = async (req: any, res: any) => {
	try {
	} catch (error: any) {
		console.log("error at saveBlog: ", error);
		res.status(500).json({
			message: error.message,
		});
	}
};

export const getSavedBlog = async (req: any, res: any) => {
	try {
	} catch (error: any) {
		console.log("error at : ", error);
		res.status(500).json({
			message: error.message,
		});
	}
};
